name: Run Server Tests

on: [push, pull_request]

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Specify your Node.js version

    # Install dependencies
    - name: Install dependencies
      run: |
        cd server
        npm install --legacy-peer-deps

    # Run tests
    - name: Run server tests
      run: |
        cd server
        npm test